/** @file magnetic_model.c
 * @author Jan Zwiener (jan@zwiener.org)
 *
 * @brief World Magnetic Model look-up (see magnetic_model.h).
 */

#include <math.h>

#include "magnetic_model.h"
#include "wmm_lut.h" /* generated by generate_wmm_grid.py */

#define WMM_DEG2RAD (0.017453292519943295f)

/* Helper function: Clamp latitude and wrap longitude into the table size, then
 * return the fractional grid cell (idx + frac in [0,1)) for a grid with the
 * given step. The idx is guaranteed to have a idx+1 neighbour. */
static void wmm_cell(float lat_deg, float lon_deg, int step, int* lat_idx, float* lat_frac,
                     int* lon_idx, float* lon_frac)
{
    if (lat_deg >= 90.0f) { lat_deg = 89.999f; }
    if (lat_deg <= -90.0f) { lat_deg = -90.0f; }
    /* Clamp longitude to [-180, 180): */
    lon_deg = fmodf(lon_deg + 180.0f, 360.0f);
    if (lon_deg < 0.0f) { lon_deg += 360.0f; }
    lon_deg -= 180.0f;
    if (lon_deg >= 180.0f) { lon_deg = 179.999f; }

    const float lat_off = lat_deg - (float)WMM_LAT_MIN;
    const float lon_off = lon_deg - (float)WMM_LON_MIN;
    const float s       = (float)step;

    *lat_idx  = (int)(lat_off / s);
    *lon_idx  = (int)(lon_off / s);
    *lat_frac = (lat_off - (float)(*lat_idx) * s) / s;
    *lon_frac = (lon_off - (float)(*lon_idx) * s) / s;
}

/* @satisfies REQ-SYS-013 */
float magnetic_declination_deg(float lat_deg, float lon_deg, float year)
{
    int   li, oi;
    float lf, of;
    wmm_cell(lat_deg, lon_deg, WMM_STEP_DEG, &li, &lf, &oi, &of);

    /* Linear interpolation/extrapolation in time between the two epochs. */
    const float tf = (year - WMM_EPOCH_START) / (WMM_EPOCH_END - WMM_EPOCH_START);

    const float v00 = (float)wmm_decl_start[li][oi] +
                      ((float)wmm_decl_end[li][oi] - (float)wmm_decl_start[li][oi]) * tf;
    const float v01 = (float)wmm_decl_start[li][oi + 1] +
                      ((float)wmm_decl_end[li][oi + 1] - (float)wmm_decl_start[li][oi + 1]) * tf;
    const float v10 = (float)wmm_decl_start[li + 1][oi] +
                      ((float)wmm_decl_end[li + 1][oi] - (float)wmm_decl_start[li + 1][oi]) * tf;
    const float v11 =
        (float)wmm_decl_start[li + 1][oi + 1] +
        ((float)wmm_decl_end[li + 1][oi + 1] - (float)wmm_decl_start[li + 1][oi + 1]) * tf;

    const float bottom = v00 + (v01 - v00) * of;
    const float top    = v10 + (v11 - v10) * of;
    return (bottom + (top - bottom) * lf) / 100.0f;
}

/* @satisfies REQ-SYS-013 */
float magnetic_inclination_deg(float lat_deg, float lon_deg)
{
    int   li, oi;
    float lf, of;
    wmm_cell(lat_deg, lon_deg, WMM_STEP_DEG_F, &li, &lf, &oi, &of);

    const float v00 = (float)wmm_incl_cdeg[li][oi];
    const float v01 = (float)wmm_incl_cdeg[li][oi + 1];
    const float v10 = (float)wmm_incl_cdeg[li + 1][oi];
    const float v11 = (float)wmm_incl_cdeg[li + 1][oi + 1];

    const float bottom = v00 + (v01 - v00) * of;
    const float top    = v10 + (v11 - v10) * of;
    return (bottom + (top - bottom) * lf) / 100.0f;
}

/* @satisfies REQ-SYS-013 */
float magnetic_field_strength_uT(float lat_deg, float lon_deg)
{
    int   li, oi;
    float lf, of;
    wmm_cell(lat_deg, lon_deg, WMM_STEP_DEG_F, &li, &lf, &oi, &of);

    const float v00 = (float)wmm_field_microTesla[li][oi];
    const float v01 = (float)wmm_field_microTesla[li][oi + 1];
    const float v10 = (float)wmm_field_microTesla[li + 1][oi];
    const float v11 = (float)wmm_field_microTesla[li + 1][oi + 1];

    const float bottom = v00 + (v01 - v00) * of;
    const float top    = v10 + (v11 - v10) * of;
    return bottom + (top - bottom) * lf;
}

/* @satisfies REQ-SYS-013 */
void magnetic_field_ned_uT(float lat_deg, float lon_deg, float year, float b_ned_uT[3])
{
    const float d = magnetic_declination_deg(lat_deg, lon_deg, year) * WMM_DEG2RAD;
    const float i = magnetic_inclination_deg(lat_deg, lon_deg) * WMM_DEG2RAD;
    const float f = magnetic_field_strength_uT(lat_deg, lon_deg);

    b_ned_uT[0] = f * cosf(i) * cosf(d); /* north */
    b_ned_uT[1] = f * cosf(i) * sinf(d); /* east  */
    b_ned_uT[2] = f * sinf(i);           /* down  */
}
